update 0.4.20

diff --git a/dv2 b/dv2
--- a/dv2
+++ b/dv2
@@ -73,7 +73,7 @@
 #   -h|--help
 #       This help, exit
 #
-#help ends here (see read_bash_help())
+#help ends here (see read_bash_docstring())
 set -euo pipefail
 shopt -s extglob globstar checkwinsize
 declare -ar PRGNAME=( DéjàVu2 DV2 dv2 )
@@ -85,7 +85,7 @@ declare -- PRG="${PRG0##*/}"
 ((EUID)) && { >&2 echo "$PRGNAME requires root."; exit 1; }
 declare -- version="$(head -qzn1 "$PRGDIR"/.version)"
 
-declare -x _TIMESTAMP=$(date +'%F_%T_%z_%Z %F %T %z %Z %A')
+declare -ax _TIMESTAMP=( $(date +'%F_%T_%z_%Z %F %T %z %Z %A') )
 declare -nx _DATE=_TIMESTAMP[1]     \
             _TIME=_TIMESTAMP[2]     \
             _TZ=_TIMESTAMP[3]       \
@@ -99,8 +99,8 @@ declare -- mdless=''
 declare -- version="$(head -qzn1 "$PRGDIR"/.version)"
 
 # basic application functions --------------------------------------------------
-# semantic helper functions
-msg()      { (($#)) || return 0; echo -n "$PRG: "; echo "$@"; }
+# #canonical semantic helper functions equivalent to `echo`
+msg()      { echo -n "$PRG: "; echo "$@"; }
 msg.info() { >&2 msg "$@"; }
 msg.err()  { >&2 msg "$@"; }
 msg.die()  { >&2 msg "$@"; exit 1; }
@@ -115,8 +115,9 @@ _declarep()  {
 }
 # declarep partnum varname
 # Returns parts of declare strings (0-3)
-# Never returns an error condition.
-# Outputs empty string on any error.
+# declare -- BASH="/usr/bin/bash"
+# Never invokes an error condition, but
+# returns an empty string for not found or error.
 # All error messages suppressed.
 declarep() {
   (($#)) || return 0;
@@ -161,15 +162,20 @@ declare -i interactive
 interactive=$(  [ -t 0 ] && echo 1 || echo 0 )
 #shellcheck disable=SC2209
 set_interactive() {
-  [[ -z "${1:-}" ]] && { _declarep interactive wordwrap less; return 0; }
-  if [[ $1 == 'on' ]] || (($1 > 0)); then
+  local -- _onoff="${1:-}"
+  if [[ -z "$_onoff" ]]; then
+    _declarep interactive wordwrap less
+  elif [[ ' on true 1 ' == *" $_onoff "* ]]; then
     interactive=1
     wordwrap=1
-    less=$(command -v less)
-  elif [[ $1 == 'off' ]] || (($1 == 0)); then
+    less=$(2>/dev/null command -v less || echo 'cat')
+  elif [[ ' off false 0 ' == *" $_onoff "* ]]; then
     interactive=0
     wordwrap=0
     less=cat
+  else
+    msg.err "FUNCNAME[0]: invalid parameter '$_onoff'"
+    return 1
   fi
 }
 declare -fx 'set_interactive'
@@ -411,27 +417,55 @@ set +e
 ##       are handled by trap_error().
 # -- end on_error --------------------------------------------------
 
-# help self-text reader
-read_bash_help() {
+read_bash_docstring() {
+# help self-text reader ---------------------------------------------
+# read_bash_docstring()
+#
+# Reads current script source file for all contiguous
+# hard-left comments at the very top of the script.
+#
+# Header comments are indicated with a leading '# '.
+#
+# Processing stops at the first non-'# ' line,
+# excepting #!hashbangs, #shellchecks and 'empty'
+# comments (^#$).
+#
+# 'empty' comments (^#$) are printed while still in
+# the header block.
+#
+# Header Comments are output minus the leading '# '.
+#
+# Note: In this version of the function, each line is
+# eval-ed, so remember to escape [`"$] chars if required.
+#
+# Note: Preferentially uses $PRG0 if found, otherwise uses $0.
+  local -- funcname="${1:-}"
+  funcname="${funcname//[ \(\)]/}"
   local -- ln
   while IFS= read -r ln; do
+    if [[ -n "$funcname" ]]; then
+        [[ $ln =~ ^[s]*[function\ ]*"${funcname}"[\s]*() ]] \
+          && funcname=''
+      continue
+    fi
     [[ ${ln:0:1} == '#' ]] || return 0
     [[ $ln == '#' ]] && { echo; continue; }
     [[ ${ln:0:2} == '# ' ]] || continue
     [[ $ln == *'shellcheck'* ]] && continue
     eval "echo \"${ln:2}\""
-  done <"$PRG0"
+  done <"${PRG0:-"$0"}"
+  >&2 echo "${FUNCNAME[0]}: Header comments not found in ${funcname:-script} ${PRG:-"$0"}"
   return 1
 }
 # Help
-#[[ " $* " == *' -h '* || " $* " == *' --help '* ]] && read_bash_help
+#[[ " $* " == *' -h '* || " $* " == *' --help '* ]] && read_bash_docstring
 
 set_readline_history_file
 
 #===================================================================
 main() {
+  # Process command line arguments and options ------------------------
   local arg1='' arg_name arg_value
-  # Process command line arguments and options
   while(($#)); do
     # var=value arguments
     if [[ "$1" =~ ^([a-zA-Z_][a-zA-Z0-9_]*)=(.*)$ ]]; then
@@ -447,17 +481,6 @@ main() {
       shift
       continue
     fi
-
-#    # var=value arguments
-#    if [[ "$1" =~ ^[a-zA-Z_][a-zA-Z0-9_]*= ]]; then
-#      arg1="${1%=*}"
-#      arg1=${arg1//-/_}
-#      [[ -z "$(_declarep "$arg1")" ]] \
-#          && { msg.err "Invalid variable declaration '$1'"; return 1; }
-#      eval "$1" || return 1
-#      shift
-#      continue
-#    fi
 
     #shellcheck disable=SC2206
     case "$1" in
@@ -523,7 +546,7 @@ main() {
                 echo "$PRGVER"; return 0
                 ;;
       -h|--help)
-                read_bash_help; return 0
+                read_bash_docstring; return 0
                 ;;
       -[mtgkMcxLlwvqiyaANVh]*) #shellcheck disable=SC2046 # de-aggregate aggregated short options
                 set -- '' $(printf -- "-%c " $(grep -o . <<<"${1:1}")) "${@:2}"
@@ -536,7 +559,7 @@ main() {
     shift
   done
 
-  # suck any stdin into Cmd_Cache[] -----------------------------------------------
+  # Suck in any stdin into the Cmd_Cache[] -----------------------------------------------
   if [[ ! -t 0 ]]; then
     # Save current stdin to a new file descriptor 3
     exec 3<&0
@@ -550,7 +573,7 @@ main() {
   fi
   ((exit_on_completion)) && Cmd_Cache+=( '/exit now' )
 
-  # Grant default user names for terminal display.
+  # Assign default user names for terminal display.
   [[ -z "$system" ]]    && system="$PRG"
   [[ -z "$user" ]]      && user="$USER@$HOSTNAME"
   [[ -z "$assistant" ]] && assistant="$model"
@@ -940,7 +963,6 @@ main() {
                 if [[ $reply == 'c' ]]; then
                   [[ ! -d "$_selected" ]] \
                     && _selected="$${_selected%/*}"
-#                    && _selected="$ (dirname -- "$_selected")"
                   cd "$_selected" || true
                   continue
                 elif [[ $reply == 'l' ]]; then
@@ -1120,11 +1142,9 @@ main() {
       fi
     fi
 
-    # Call openai
+    # Call openai -----------------------------------------
     local -- _PD_expanded
     eval "_PD_expanded=\"${primary_directive}\""
-    # Print the expanded directive
-    #echo "$directive_expanded"
     content=$($openai api chat.completions.create \
         --model        "$model" \
         --n            "$n" \
@@ -1285,7 +1305,6 @@ print_script_command_help() {
     && Script_Command_Help=$(get_script_command_help)
   echo "$Script_Command_Help" | $less
 }
-
 
 main "$@"
 #fin
